config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: database
      host: 192.168.7.120
      pass: meeko
      port: 5433
      schema: public
      threads: 8
      type: postgres
      user: meeko
  target: prod
